#!/usr/bin/env python

import csv
from Bio import SeqIO
import codecs
from pytools.persistent_dict import PersistentDict
import os

##### Configuration #####

if config.get("representative_aln"):
    config["representative_aln"] = os.path.join(workflow.current_basedir,'..', config["representative_aln"])

if config.get("guide_tree"):
    config["guide_tree"] = os.path.join(workflow.current_basedir,'..', config["guide_tree"])

if config.get("lineages_csv"):
    lineages_csv_path = os.path.join(workflow.current_basedir,'..', config["lineages_csv"])
    config["lineages_csv"]=f"lineages_csv={lineages_csv_path} "
else:
    config["lineages_csv"]=""

if not config.get("write_tree"):
    config["write_tree"]="False"

    
if config.get("force"):
    config["force"] = "--forceall "
else:
    config["force"] = ""
    
config["pid"] = str(os.getpid())

##### Target rules #####

rule all:
    input:
        config["outdir"] + "/lineage_report.csv"

##### Modules #####
include: "assign_query_file.smk"
