name: pangolin-ubuntu
on: [push, pull_request]
defaults:
  run:
    shell: bash -l {0}

jobs:
  run_pangolin_test:
    name: Pangolin test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml
          activate-environment: pangolin
          channels: conda-forge,bioconda,defaults
      - name: Install pangolin
        run: pip install -e .
      - name: Check pangolin version
        run: pangolin --version
      - name: Run pangolin with test data
        run: pangolin pangolin/test/test_seqs.fasta 2>&1 | tee pangolin.log
      - name: Compare assigned lineages (first two columns only) with expected values
        run: cut -d, -f1,2 lineage_report.csv | diff - pangolin/test/test_seqs.assignments.csv
      - name: Run pangolin with test zip data
        run: pangolin pangolin/test/test_seqs.fasta.gz 2>&1 | tee pangolin_zip.log
      - name: Run pangolin with test all cache data
        run: pangolin pangolin/test/all_bad_seqs.fasta 2>&1 | tee pangolin_all_bad.log
      - name: Run pangolin with test all bad data
        run: pangolin pangolin/test/all_hash.fasta 2>&1 | tee pangolin_cache.log
      - name: Run pangolin usher with test data
        run: pangolin --analysis-mode usher pangolin/test/test_seqs.fasta 2>&1 | tee pangolin_usher.log
      - name: Run pangolin accurate with test data
        run: pangolin --analysis-mode accurate pangolin/test/test_seqs.fasta 2>&1 | tee pangolin_accurate.log
      - name: Run pangolin with outdir and outfile
        run: pangolin pangolin/test/test_seqs.fasta -o my_test --outfile pangolin_out.txt 2>&1 | tee pangolin_outdir_outfile.log
      - name: Run pangolin with out alignment
        run: pangolin pangolin/test/test_seqs.fasta --alignment --alignment-file my_alignment.fasta 2>&1 | tee pangolin_alignment.log
      - name: Run pangolin aliases
        run: pangolin --aliases  2>&1  | tee pangolin_alias.log
      - name: Run pangolin all versions
        run: pangolin --all-versions  2>&1  | tee pangolin_versions.log
      - name: Run pangolin skip designation cache
        run: pangolin  pangolin/test/test_seqs.fasta --skip-designation-cache   2>&1  | tee pangolin_no_cache.log
      - name: Run pangolin update 
        run: pangolin --update   2>&1  | tee pangolin_update.log
      - name: Run pangolin update data
        run: pangolin --update-data   2>&1  | tee pangolin_update_data.log
      - name: Run pangolin verbose mode
        run: pangolin --verbose  pangolin/test/test_seqs.fasta  2>&1  | tee pangolin_verbose.log
      - name: Add assignment cache
        run: pangolin --add-assignment-cache
      - name: remove assignment cache
        run: pip uninstall -y pangolin-assignment
